---
# tasks file for wkhtmltopdf
- name: get deb pkg
  get_url:
    url: http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
    dest: "/home/{{ owner }}/wkhtmltopdf.deb"
- name: run dpkg -i install
  apt:
    deb: "/home/{{ owner }}/wkhtmltopdf.deb"
- name: run apt-get install -f to install additional deps
  command: "sudo apt-get install -f"
